version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MY_SQL_DATABASE: igcommerce
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
